//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hora.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Ver_la_hora", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://Ver_la_hora is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Ver_la_hora/HelloWorld", ReplyAction="*")]
        Hora.ServiceReference1.HelloWorldResponse HelloWorld(Hora.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ver_la_hora/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Hora.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Hora.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name HoraResult from namespace http://Ver_la_hora is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Ver_la_hora/Hora", ReplyAction="*")]
        Hora.ServiceReference1.HoraResponse Hora(Hora.ServiceReference1.HoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ver_la_hora/Hora", ReplyAction="*")]
        System.Threading.Tasks.Task<Hora.ServiceReference1.HoraResponse> HoraAsync(Hora.ServiceReference1.HoraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://Ver_la_hora", Order=0)]
        public Hora.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Hora.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://Ver_la_hora", Order=0)]
        public Hora.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Hora.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Ver_la_hora")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Hora", Namespace="http://Ver_la_hora", Order=0)]
        public Hora.ServiceReference1.HoraRequestBody Body;
        
        public HoraRequest() {
        }
        
        public HoraRequest(Hora.ServiceReference1.HoraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HoraRequestBody {
        
        public HoraRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HoraResponse", Namespace="http://Ver_la_hora", Order=0)]
        public Hora.ServiceReference1.HoraResponseBody Body;
        
        public HoraResponse() {
        }
        
        public HoraResponse(Hora.ServiceReference1.HoraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Ver_la_hora")]
    public partial class HoraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HoraResult;
        
        public HoraResponseBody() {
        }
        
        public HoraResponseBody(string HoraResult) {
            this.HoraResult = HoraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Hora.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Hora.ServiceReference1.WebService1Soap>, Hora.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hora.ServiceReference1.HelloWorldResponse Hora.ServiceReference1.WebService1Soap.HelloWorld(Hora.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Hora.ServiceReference1.HelloWorldRequest inValue = new Hora.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Hora.ServiceReference1.HelloWorldRequestBody();
            Hora.ServiceReference1.HelloWorldResponse retVal = ((Hora.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hora.ServiceReference1.HelloWorldResponse> Hora.ServiceReference1.WebService1Soap.HelloWorldAsync(Hora.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hora.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Hora.ServiceReference1.HelloWorldRequest inValue = new Hora.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Hora.ServiceReference1.HelloWorldRequestBody();
            return ((Hora.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hora.ServiceReference1.HoraResponse Hora.ServiceReference1.WebService1Soap.Hora(Hora.ServiceReference1.HoraRequest request) {
            return base.Channel.Hora(request);
        }
        
        public string Hora() {
            Hora.ServiceReference1.HoraRequest inValue = new Hora.ServiceReference1.HoraRequest();
            inValue.Body = new Hora.ServiceReference1.HoraRequestBody();
            Hora.ServiceReference1.HoraResponse retVal = ((Hora.ServiceReference1.WebService1Soap)(this)).Hora(inValue);
            return retVal.Body.HoraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hora.ServiceReference1.HoraResponse> Hora.ServiceReference1.WebService1Soap.HoraAsync(Hora.ServiceReference1.HoraRequest request) {
            return base.Channel.HoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hora.ServiceReference1.HoraResponse> HoraAsync() {
            Hora.ServiceReference1.HoraRequest inValue = new Hora.ServiceReference1.HoraRequest();
            inValue.Body = new Hora.ServiceReference1.HoraRequestBody();
            return ((Hora.ServiceReference1.WebService1Soap)(this)).HoraAsync(inValue);
        }
    }
}
